### ISSUE TITLE
Why is the wallet using 1 core 100% all the time?

### ISSUE THREAD

**Issue by Fluffkin** [dobbscoin/dobbscoin-source#16]
It looks like it's trying to mine on 1 core, but setting gen=0 doesn't help.
Gentoo Linux, compiled github source.

**Comment by dobbscoin** [comment]
Hmmm, not alot of information to go on.
I can tell you that gen=0 will not help, as zero means NO.

DobbsCoin is a scrypt coin, and likely has far too much combined hash to ever find a block using a single core CPU wallet mining setup.  I remember on the very first day, I was finding blocks that way, but my two wallets were all the hash on the network.  These days, in order to find a block I have to fire up some gridseed miners or use a larger rig and mine on the pool.  

For instance: http://pool.dobbscoin.info/index.php?page=statistics&action=pool
Romes is mining alone at the pool @ 3MB/s and it's been 14hrs since he's found a block.

I usually referr folks to Google: Scrypt Mining / Pool Mining Altcoins.
If you can't whoop it - You'll go down. Good luck to you.

Freenode IRC #Dobbscoin

**Comment by Earlz** [comment]
Hmm, it shouldn't try to mine by default. Are you using the latest wallet, and is there anything interesting in ~/.dobbscoin/debug.log ? Also, I assume it's already synced completely right?

**Comment by Fluffkin** [comment]
I'm not sure it was mining, it was just a guess at what might be using a core at 100%.
Neither am I trying to CPU mine with it! O.o
Yes it's the latest wallet (compiled from a git clone from here).
Yes it's completely sync'd.
Debug log shows nothing unusual.
I have about 30 other scrypt wallets compiled from source on here, and none of them use a core at 100% all the time. I just thought someone else might have noticed it.

**Comment by Fluffkin** [comment]
I've tracked it down to the "openconnection" thread, and it's not the MilliSleep within that hogging CPU. Other coins seem to have a fail check in the open connection thread that Dobbs doesn't have. I've not got much further than that though.

**Comment by Fluffkin** [comment]
Fix found here : https://github.com/zcash/zcash/pull/929/commits/b0f75847eaf5a85cd614c4f990f20172ad8185fc

**Comment by dobbscoin** [comment]
Tracked it down to the "openconnection" thread aye, we'll see what "BOB" has to say about this.
Thanks for lookin out. 

You do any coin work?
